<!-- 2025-10-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Refactor the `Alignet_Paymecheckout` module": https://github.com/innomuebles/m2/issues/10 -->
<?php
use Dfe\Alignet\Cfg;
$c = dfe_alignet_cfg(); /** @var Cfg $c */
?>
<link
	href='<?= $c->url('css/modalcomercio.css') ?>'
	id='alignet-modal-css'
	media='all'
	rel='stylesheet'
	type='text/css'
/>
<script src='<?= $c->url('js/modalcomercio.js') ?>' type='text/javascript'></script>
<form 
	action='<?= $c->urlStart() ?>'
	class='alignet-form-vpos2'
	id='f1' 
	method='POST' 
	name='f1' 
>
    <?php foreach ($this->getOrderCreateData() as $name => $value): ?>
    	<input type="hidden" name="<?= $name; ?>" value="<?= $value; ?>" />
    <?php endforeach; ?>
    <input
		id="btnmodal"
		onclick="<?= $c->urlStart(); ?>"
		style="display:none;"
		type="button"
		value="Comprar"
	/>
</form>
<script>document.forms['f1'].submit();</script>