<style type="text/css">
	.title.success {
	color: green;
	font-weight: bold;
}

	.title.danger {
	color: red;
	font-weight: bold;
}

.pagoefectivo-cip {
	font-weight: bold;
	text-transform: uppercase;
	font-size: 20px;
	color: #333;
	padding-top: 10px;
	text-align: center;
}



</style>


<?php 

$response = $this->getPostdata();

?>

<div class="card-block">
		<div class="row">
		  <div class="col-md-12">
 <div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<div class="col-sm-12">
			<h2 class="title <?= $response['titleColor'];?> text-center">
				<i class="fa fa-check-circle" aria-hidden="true"></i> <?= $response['answerMessage']; ?>
			</h2>
		</div>
		
			<p class="text-center">
				<?= $response['msgNumeroOP']; ?>
			</p>
			<hr>
						
			<div class="row">
				<section class="address-delivery col-sm-4 col-sm-offset-1">
					<h4 class="subtitle"><i class="icon icon-cc-visa" aria-hidden="true"></i><b> Respuesta de Pay-me</b></h4>
					<ul>
						<li><b>Marca: </b><?= $response['brand']; ?></li>													<li><b>Tarjeta: </b><?= $response['paymentReferenceCode']; ?> </li> 
																			<li><b> Respuesta: </b> <?= $response['responseMSG'];?> </li>
											</ul>
				</section>
				<section class="payment-datails col-sm-4 col-sm-offset-1">
					<h4 class="subtitle"><i class="icon icon-credit-card"></i><b> Detalles de pago</b></h4>
					<ul>
						<li class="total">
							Número de operación:
							<span class="pull-right">  <?= $response['purchaseOperationNumber'] ?> </span>
						</li>
						<li class="total">
							Importe Total: <span class="pull-right"> <?= $response['purchaseCurrencyCode'].'  '.number_format((int)($response['purchaseAmount']/100),2); ?></span>
						</li>
					</ul>
				</section>
			</div>
			<br>
			<div class="row">
				<section class="details col-sm-12">
					<br>
					<p><?= $response['msgFecha']; ?>
					</p>
					<br>
				</section>
			</div>

				<table class="table">
			<thead>
				<tr>

					<th>Productos del pedido:</th>
				</tr>
			</thead>
			<tbody>
								<tr>
					<td> <?= $response['descriptionProducts']; ?> </td>
				</tr>
							</tbody>
		</table>
	</div>
</div>
<div class="row">
	<section class="col-sm-12">
		<h4 class="subtitle"><b><i class="icon icon-question-circle" aria-hidden="true"></i>¿Dudas o Consultas?</b></h4>
		<ul>
			<li><i class="fa fa-angle-double-right" aria-hidden="true"></i> Si deseas conocer acerca tus derechos
			como consumidor puedes ingresar a nuestra página de
				<a href="https://www.pay-me.com/es/" class="iframe" target="_blank">
					Términos y Condiciones.
				</a>
			</li>
			<li>
				<i class="fa fa-angle-double-right" aria-hidden="true"></i>
				Contamos con un equipo de expertos que te ayudarán a resolver todas tus dudas o consultas presentadas
				respecto a este pedido. Ingresa a nuestro
				<a href="https://www.pay-me.com/es/">
					Centro de Atención al Cliente
				</a>.
			</li>
		</ul>
	</section>
</div>
		  </div>
		</div>
	  </div>